import type { Metadata } from "next";
import { Catamaran } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/Sidebar";

const inter = Catamaran({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Project Planner Ai !!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen flex flex-col items-center text-white bg-black/90`}
      >
        {/* <Navbar /> */}
        {/* <Sidebar/> */}
        {children}
      </body>
    </html>
  );
}
